### ISSUE TITLE
April Edition

### ISSUE THREAD

**Issue by OleMchls** [hh-ex/planning#6]
- [x] Create meetup.com event
- [x] Agenda
- [x] prepare katas if applicable
- [x] Location
- [x] Format
- [x] Announce meetup.com event (triggers mail)

**Date:** April 26th
**Location:** SABIO with @dszam

Agenda: 
- 18:00 Open the doors 
- 18:30 Welcome 
- Talk by @BjRo "Basics of Metaprogramming in Elixir" #5
- meta programming coding (kata / dojo)

**Comment by LydG** [comment]
Idea: Having @BjRo giving the talk proposed in #5 plus some coding things we might come up with later

**Comment by OleMchls** [comment]
As discussed in #5 the programming exercise could/should relate to the meta programming talk

**Comment by BjRo** [comment]
@nesQuick It looks like we have to re-arrange regarding the location (at least a bit). 

I talked to the office ladies again this morning and received some new, unfortunate news. Our meetup room at XING is booked for another event until 18:00 on the 26.04. (That part I was aware of and thought it wasn't a problem). The new part for me is that the event is organized together with an external agency and the cleanup of the room will take >= 1h. I'm currently talking with the involved parties. 

One option would be to move our meetup one hour backwards to 19:30. I think that should work (but I'll clarify this tomorrow). The less sexy alternatives would be switching to a different day or month. What's your preference on this?

**Comment by markschmidt** [comment]
We could also use one of the bigger meeting rooms (like Reeperbahn / space for 20 people). I think even with a few more people then yesterday, it would work quite good. And the chairs are much better then what we would sit on in the event room.

Assuming of course the room is free that evening.

**Comment by BjRo** [comment]
@markschmidt Yeah, thought about that as well.  Might be harder to navigate external people to rooms other than the event room, tough :-)

**Comment by markschmidt** [comment]
Mh, true... That's not ideal.

**Comment by dszam** [comment]
I could check tomorrow, if our Lounge is free on 26.04. We then could just swap the meetings. Then you would host it on may 31st.

**Comment by BjRo** [comment]
@dszam Awesome, that sounds like a plan. I'll check tomorrow whether the May 31st is available on our side.

**Comment by OleMchls** [comment]
@dszam @BjRo yup, awesome <3

**Comment by dszam** [comment]
allrighty! From my side everything is ready to host the meetup on 26.04. at SABIO.

Cheers Dirk

**Comment by BjRo** [comment]
Fixed on our side as well. We're switching to 31st of May. We'll only have to start 30min later (letting people in at 18:30 and starting at 19:00) because there's also another appointment in the room before us. This time no big cleanup necessary though :)

Special thx to @dszam for making this switch possible!

**Comment by OleMchls** [comment]
@dszam @BjRo alright, awesome. Glad it worked out that easily :) Just adjusted meetup.com and github :+1:

**Comment by OleMchls** [comment]
finished the description on meetup.com and also announced it (still not sure what this _really_ does, tho)

**Comment by h4cc** [comment]
I've send a tweet today: https://twitter.com/HamburgEx/status/723822183659745280
Plan to send another reminder on monday.

**Comment by h4cc** [comment]
This meetup is mentioned in the Elixir Newsletter Issue 46: https://app.rdstation.com.br/mail/3bf0988a-8afe-4862-acdb-73255024fb48

**Comment by BjRo** [comment]
While searching for some additional Katas for us (turns out finding a metaprogramming kata is pretty hard) I stumbled over http://exercism.io/languages/elixir. 

If we don't come up with something kata-wise, always a good fallback. `anagram` for example seems to be matching our current group expertise quite well.

**Comment by OleMchls** [comment]
@h4cc yeah, I've talked with Plataformatec, we will be in all future Elixir Radar newsletters, they somehow extract infos from meet up. Also huge thanks for the tweet and talking care of the account, for a second I was surprised who the account came to this tweet but then I remembered 😆

**Comment by OleMchls** [comment]
@BjRo yeah, we don't have a kata for tomorrow yet. bus this is what I want to do now. If you have something in mind which related to your talk, even from exercism.io please let me know :)

**Comment by OleMchls** [comment]
Brain dump: that's a great one for Elixir 1.3 http://exercism.io/exercises/elixir/meetup/readme

**Comment by BjRo** [comment]
So, I didn't find anything kata like in regard to macros / meta programming. The meetup kata is definitely interesting. Haven't played with the new Date, Calender modules yet. Feel free to pick!

**Comment by dszam** [comment]
@nesQuick are there any templates for the location "signs" where to meet or shall I do it freestyle?

**Comment by OleMchls** [comment]
Just go freestyle. I could also send you our logo tomorrow

**Comment by dszam** [comment]
@nesQuick it would be fine, if you could upload it in the repository

**Comment by OleMchls** [comment]
@dszam just added the logos https://github.com/hh-ex/planning/tree/master/logo sorry for the short notice :)

**Comment by OleMchls** [comment]
I did a quick n dirty kata http://bit.ly/hhex-kata-april-2016 I think this one is going to be fun!
